Test ajout livraison
IssouProjects/PLD-Agile pull request #161
Opened 2017-10-28 17:06 UTC by AmosTrask

2017-10-28 17:06 UTC, AmosTrask commented
Il y a rien à ajouter pour que Travis utilise les nouveaux tests ?

2017-10-28 18:17 UTC, TimotheeDurand submitted a review, later dismissed

2017-10-28 18:32 UTC, Raul6469 requested changes
C'est bien, mais il y a juste le classpath à ne pas changer, et ça doit être un fichier de test par classe à mon avis, donc perso je mettrais ces tests dans TestTournee. Et ouais, Travis se débrouille tout seul, tu pourras vérifier dans les logs

2017-10-29 12:22 UTC, AmosTrask commented
Moi je préfère faire un fichier par cas d'utilisation, çà me parait plus adéquat vis à vis de ce qui est demandé par les profs. Et çà sera plus facile de s'y retrouver

2017-10-29 12:23 UTC, Raul6469 approved these changes

2017-10-29 12:24 UTC, merged