Vue graphique
IssouProjects/PLD-Agile pull request #44
Opened 2017-10-15 21:26 UTC by TimotheeDurand

Cette branche contient la première version de l'interface de notre application.

Pour l'instant, ça n'affiche rien de particulier, mais tout est déjà là pour afficher un PlanDeVille. Il faudra juste faire le lien avec le contrôleur.

2017-10-15 21:27 UTC, TimotheeDurand commented
MDR ça compile même pas

2017-10-15 21:29 UTC, TimotheeDurand commented
Je préfère ça...

2017-10-15 21:31 UTC, Raul6469 requested changes
A voir après intégration avec le reste de l'archi

2017-10-16 12:51 UTC, Raul6469 commented on project/src/main/java/org/apache/project/controleur/Controleur.java
> +		}
Ça devrait pas renvoyer une erreur si on essaie de `getInstance` quand `instance` n'est pas encore instanciée ? En tout cas ça fait plus qu'un simple `get`

2017-10-16 13:01 UTC, AmosTrask commented on project/src/main/java/org/apache/project/controleur/Controleur.java
> +		}
Nop, si ya pas d'instance, une instance est créé, c'est le principe d'un singleton

2017-10-16 13:01 UTC, AmosTrask commented on project/src/main/java/org/apache/project/controleur/Controleur.java
> +		}
Tu ne sais pas qui va instancier le singleton en premier

2017-10-16 13:02 UTC, Raul6469 commented on project/src/main/java/org/apache/project/controleur/Controleur.java
> +		}
Ok, my bad

2017-10-16 13:12 UTC, Raul6469 approved these changes

2017-10-16 14:20 UTC, merged